project.build.sourceEncoding=UTF-8
amidst.build.jdk.version=17
amidst.build.filename=amidst-gtnh-biomes-v0-2-v25

amidst.version.major=4
amidst.version.minor=7
amidst.version.patch=0
amidst.version.preReleaseSuffix=gtnh-biomes-0.2
