package amidst.gtnh.worker.mod;

import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Seed-only predictors for structures generated by GTNH mods through Forge's
 * IWorldGenerator hook.
 */
final class ModStructurePredictor {

    private static final int NETHER = -1;
    private static final int OVERWORLD = 0;
    private static final int LOOTGAMES_MARKER_OFFSET = 8;
    private static final int SLIME_ISLAND_MARKER_OFFSET = 16;
    private static final int AUTOMAGY_SPIRE_MIN_OFFSET = 4;
    private static final int AUTOMAGY_SPIRE_MAX_OFFSET = 9;
    private static final int MAX_CHUNKS = 262144;

    private final Object lootGamesWorldGenConfig;
    private final Field lootGamesDisabled;
    private final Method lootGamesDimensionEnabled;
    private final Method lootGamesRhombusSize;
    private final Method slimeIslandDimensionEnabled;
    private final Field slimeIslandRarity;
    private final Field automagyNetherSpireChance;
    private final Ae2MeteoritePredictor ae2MeteoritePredictor;

    ModStructurePredictor() {
        try {
            Class<?> lootGamesConfigs =
                    Class.forName("ru.timeconqueror.lootgames.common.config.LGConfigs");
            Object general = lootGamesConfigs.getField("GENERAL").get(null);
            Field worldGen = general.getClass().getField("worldGen");
            lootGamesWorldGenConfig = worldGen.get(general);
            Class<?> worldGenClass = lootGamesWorldGenConfig.getClass();
            lootGamesDisabled = worldGenClass.getField("disableDungeonGen");
            lootGamesDimensionEnabled =
                    worldGenClass.getMethod("isDimensionEnabledForWG", Integer.TYPE);
            lootGamesRhombusSize =
                    worldGenClass.getMethod("getWorldGenRhombusSize", Integer.TYPE);

            Class<?> dimensionBlacklist =
                    Class.forName("tconstruct.util.config.DimensionBlacklist");
            slimeIslandDimensionEnabled =
                    dimensionBlacklist.getMethod("isDimInBlacklist", Integer.TYPE);
            Class<?> phConstruct = Class.forName("tconstruct.util.config.PHConstruct");
            slimeIslandRarity = phConstruct.getField("islandRarity");
            Field spireChance;
            try {
                Class<?> automagyConfig =
                        Class.forName("tuhljin.automagy.lib.AutomagyConfig");
                spireChance = automagyConfig.getField("netherSpireChance");
            } catch (ClassNotFoundException e) {
                spireChance = null;
            } catch (NoSuchFieldException e) {
                spireChance = null;
            }
            automagyNetherSpireChance = spireChance;
            ae2MeteoritePredictor = new Ae2MeteoritePredictor();
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException(
                    "LootGames or Tinkers' Construct structure prediction API is unavailable",
                    e);
        }
    }

    List<RoguelikeDungeonPredictor.StructureDescriptor> predict(
            long seed,
            int dimension,
            int minX,
            int minZ,
            int width,
            int height) {
        if (dimension != OVERWORLD && dimension != NETHER) {
            throw new IllegalArgumentException(
                    "mod structure prediction supports only overworld dimension 0 and Nether dimension -1");
        }

        long maxX = (long) minX + width;
        long maxZ = (long) minZ + height;
        List<RoguelikeDungeonPredictor.StructureDescriptor> result =
                new ArrayList<RoguelikeDungeonPredictor.StructureDescriptor>();
        if (dimension == OVERWORLD) {
            addLootGamesDungeons(seed, dimension, minX, minZ, maxX, maxZ, result);
        }
        addSlimeIslands(seed, dimension, minX, minZ, maxX, maxZ, result);
        if (dimension == OVERWORLD) {
            result.addAll(ae2MeteoritePredictor.predict(
                    seed,
                    dimension,
                    minX,
                    minZ,
                    width,
                    height));
        } else {
            addAutomagyNetherSpires(seed, minX, minZ, maxX, maxZ, result);
        }
        return result;
    }

    private void addLootGamesDungeons(
            long seed,
            int dimension,
            int minX,
            int minZ,
            long maxX,
            long maxZ,
            List<RoguelikeDungeonPredictor.StructureDescriptor> result) {
        if (getBoolean(lootGamesDisabled, lootGamesWorldGenConfig)
                || !invokeBoolean(
                        lootGamesDimensionEnabled,
                        lootGamesWorldGenConfig,
                        dimension)) {
            return;
        }
        int rhombusSize =
                invokeInt(lootGamesRhombusSize, lootGamesWorldGenConfig, dimension);
        if (rhombusSize < 5 || rhombusSize > 100) {
            throw new IllegalStateException(
                    "LootGames returned invalid overworld rhombus size " + rhombusSize);
        }

        ChunkBounds chunks = chunkBounds(
                minX,
                minZ,
                maxX,
                maxZ,
                LOOTGAMES_MARKER_OFFSET);
        validateChunkCount(chunks);
        for (int chunkZ = chunks.minZ; chunkZ <= chunks.maxZ; chunkZ++) {
            for (int chunkX = chunks.minX; chunkX <= chunks.maxX; chunkX++) {
                if (!isLootGamesCandidate(seed, chunkX, chunkZ, rhombusSize)) {
                    continue;
                }
                long markerX = (long) chunkX * 16L + LOOTGAMES_MARKER_OFFSET;
                long markerZ = (long) chunkZ * 16L + LOOTGAMES_MARKER_OFFSET;
                if (inside(markerX, markerZ, minX, minZ, maxX, maxZ)) {
                    result.add(descriptor(
                            "LOOTGAMES_DUNGEON",
                            (int) markerX,
                            (int) markerZ,
                            "POSSIBLE"));
                }
            }
        }
    }

    private void addSlimeIslands(
            long seed,
            int dimension,
            int minX,
            int minZ,
            long maxX,
            long maxZ,
            List<RoguelikeDungeonPredictor.StructureDescriptor> result) {
        if (!invokeBoolean(slimeIslandDimensionEnabled, null, dimension)) {
            return;
        }
        int rarity = getInt(slimeIslandRarity, null);
        if (rarity < 1) {
            throw new IllegalStateException(
                    "Tinkers' Construct returned invalid slime island rarity " + rarity);
        }

        ChunkBounds chunks = chunkBounds(
                minX,
                minZ,
                maxX,
                maxZ,
                SLIME_ISLAND_MARKER_OFFSET);
        validateChunkCount(chunks);
        for (int chunkZ = chunks.minZ; chunkZ <= chunks.maxZ; chunkZ++) {
            for (int chunkX = chunks.minX; chunkX <= chunks.maxX; chunkX++) {
                Random random =
                        RoguelikeDungeonPredictor.forgeChunkRandom(seed, chunkX, chunkZ);
                if (random.nextInt(rarity) != 0) {
                    continue;
                }
                // Islands extend roughly 20-32 blocks from the generator's
                // chunk origin. A +16 marker is a stable, useful center point.
                long markerX = (long) chunkX * 16L + SLIME_ISLAND_MARKER_OFFSET;
                long markerZ = (long) chunkZ * 16L + SLIME_ISLAND_MARKER_OFFSET;
                if (inside(markerX, markerZ, minX, minZ, maxX, maxZ)) {
                    result.add(descriptor(
                            dimension == NETHER
                                    ? "TINKERS_NETHER_SLIME_ISLAND"
                                    : "TINKERS_SLIME_ISLAND",
                            (int) markerX,
                            (int) markerZ,
                            "EXPECTED"));
                }
            }
        }
    }

    private void addAutomagyNetherSpires(
            long seed,
            int minX,
            int minZ,
            long maxX,
            long maxZ,
            List<RoguelikeDungeonPredictor.StructureDescriptor> result) {
        if (automagyNetherSpireChance == null) {
            return;
        }
        int chance = getInt(automagyNetherSpireChance, null);
        if (chance <= 0) {
            return;
        }

        ChunkBounds chunks = new ChunkBounds(
                floorDiv((long) minX - AUTOMAGY_SPIRE_MAX_OFFSET, 16),
                floorDiv(maxX - 1L - AUTOMAGY_SPIRE_MIN_OFFSET, 16),
                floorDiv((long) minZ - AUTOMAGY_SPIRE_MAX_OFFSET, 16),
                floorDiv(maxZ - 1L - AUTOMAGY_SPIRE_MIN_OFFSET, 16));
        validateChunkCount(chunks);
        for (int chunkZ = chunks.minZ; chunkZ <= chunks.maxZ; chunkZ++) {
            for (int chunkX = chunks.minX; chunkX <= chunks.maxX; chunkX++) {
                Random random =
                        RoguelikeDungeonPredictor.forgeChunkRandom(seed, chunkX, chunkZ);
                if (random.nextInt(chance) != 0) {
                    continue;
                }
                // Automagy first chooses x/z in [chunk origin, origin + 5].
                // The spire's functional center is four blocks farther along
                // each axis. Final placement still requires a suitable lava
                // pool and enough air above it.
                long markerX = (long) chunkX * 16L + random.nextInt(6) + 4L;
                long markerZ = (long) chunkZ * 16L + random.nextInt(6) + 4L;
                if (inside(markerX, markerZ, minX, minZ, maxX, maxZ)) {
                    result.add(descriptor(
                            "AUTOMAGY_NETHER_SPIRE",
                            (int) markerX,
                            (int) markerZ,
                            "POSSIBLE"));
                }
            }
        }
    }

    private static boolean isLootGamesCandidate(
            long seed,
            int chunkX,
            int chunkZ,
            int rhombusSize) {
        int divisor = rhombusSize * 2;
        int xc = chunkX * 2 + chunkZ;
        int zc = chunkZ * 2 + chunkX;
        Random random = new Random();
        random.setSeed(seed + xc / divisor + ((zc / divisor) << 14));
        int pos1 = 3 + random.nextInt(divisor - 3);
        int pos2 = 3 + random.nextInt(divisor - 3);
        int modX = properMod(xc, divisor);
        int modZ = properMod(zc, divisor);
        return modX >= 3
                && modZ >= 3
                && ((modX == pos1 && modZ == pos2)
                        || (modX == pos1 + 1
                                && (modZ == pos2 || modZ == pos2 + 1)));
    }

    private static ChunkBounds chunkBounds(
            int minX,
            int minZ,
            long maxX,
            long maxZ,
            int markerOffset) {
        return new ChunkBounds(
                floorDiv((long) minX - markerOffset, 16),
                floorDiv(maxX - 1L - markerOffset, 16),
                floorDiv((long) minZ - markerOffset, 16),
                floorDiv(maxZ - 1L - markerOffset, 16));
    }

    private static void validateChunkCount(ChunkBounds chunks) {
        long count = ((long) chunks.maxX - chunks.minX + 1L)
                * ((long) chunks.maxZ - chunks.minZ + 1L);
        if (count > MAX_CHUNKS) {
            throw new IllegalArgumentException("structure query covers too many mod-generation chunks");
        }
    }

    private static RoguelikeDungeonPredictor.StructureDescriptor descriptor(
            String kind,
            int x,
            int z,
            String certainty) {
        return new RoguelikeDungeonPredictor.StructureDescriptor(
                kind,
                "",
                x,
                z,
                certainty);
    }

    private static boolean inside(
            long x,
            long z,
            int minX,
            int minZ,
            long maxX,
            long maxZ) {
        return x >= minX && x < maxX && z >= minZ && z < maxZ;
    }

    private static int properMod(int value, int divisor) {
        int result = value % divisor;
        return result < 0 ? result + divisor : result;
    }

    private static int floorDiv(long value, int divisor) {
        long result = Math.floorDiv(value, (long) divisor);
        if (result < Integer.MIN_VALUE || result > Integer.MAX_VALUE) {
            throw new IllegalArgumentException("structure query coordinate is outside supported range");
        }
        return (int) result;
    }

    private static boolean getBoolean(Field field, Object target) {
        try {
            return field.getBoolean(target);
        } catch (IllegalAccessException e) {
            throw new IllegalStateException("cannot read mod structure boolean setting", e);
        }
    }

    private static int getInt(Field field, Object target) {
        try {
            return field.getInt(target);
        } catch (IllegalAccessException e) {
            throw new IllegalStateException("cannot read mod structure integer setting", e);
        }
    }

    private static boolean invokeBoolean(Method method, Object target, int argument) {
        try {
            return ((Boolean) method.invoke(target, Integer.valueOf(argument))).booleanValue();
        } catch (IllegalAccessException e) {
            throw new IllegalStateException("cannot read mod structure dimension setting", e);
        } catch (InvocationTargetException e) {
            Throwable cause = e.getCause() == null ? e : e.getCause();
            throw new IllegalStateException("mod structure dimension setting failed", cause);
        }
    }

    private static int invokeInt(Method method, Object target, int argument) {
        try {
            return ((Integer) method.invoke(target, Integer.valueOf(argument))).intValue();
        } catch (IllegalAccessException e) {
            throw new IllegalStateException("cannot read mod structure integer setting", e);
        } catch (InvocationTargetException e) {
            Throwable cause = e.getCause() == null ? e : e.getCause();
            throw new IllegalStateException("mod structure integer setting failed", cause);
        }
    }

    private static final class ChunkBounds {

        private final int minX;
        private final int maxX;
        private final int minZ;
        private final int maxZ;

        private ChunkBounds(int minX, int maxX, int minZ, int maxZ) {
            this.minX = minX;
            this.maxX = maxX;
            this.minZ = minZ;
            this.maxZ = maxZ;
        }
    }
}
